#!/bin/bash

SESSIONS=(
    "_" \
    "py" \
    #"mojo" \
    #"go"
)

function session_exists {
    if tmux list-sessions | grep "$1"; then
        return 0
    else
        return 1
    fi
}

function __session {
    # Start the first session and split windows
    tmux new-session -d -s "$1"
    tmux rename-window -t 1 'main'

    # open htop on the first pane
    tmux send-keys -t 0 'htop' C-m

    tmux split-window -v

    # 2 splits & weather
    tmux split-window -h
    tmux send-keys -t 2 'weather' C-m

    # open a new window in dotfiles
    tmux new-window -t $1:2 -n 'dotfiles' -c "$HOME/.dotfiles/"

    #tmux new-window -t $SESSION:3 -n 'zk' -c "$HOME/.zettelkasten/"
    #tmux send-keys -t 'zk' 'journal' C-m
}

function py_session {
    # Start a python session with conda
    tmux new-session -d -s "$1" -e "CONDA_INIT=True" -c "$HOME/Documents/Python/"
}

function mojo_session {
    tmux new-session -d -s "$1" -c "$HOME/Documents/mojo/"
}

function go_session {
    tmux new-session -d -s "$1" -c "$HOME/Documents/golang/"
}

for s in ${SESSIONS[@]}; do
    # Only start new sessions if they don't already exist
    if [[ -z $(session_exists $s) ]]; then
        func="$s"_session
        ${func} "$s"
    fi
done

# attach to session 1 if not already attached to a session
if [[ -z $(echo $TMUX) ]]; then
    tmux attach-session -t 0:1
fi
