#!/usr/bin/env bash

set -e
cd ~/.dotfiles/nixos
git diff -U0 **/*.nix
echo "Rebuilding ❄️NixOS..."
sudo nixos-rebuild switch --flake --impure .#xps &>nixos-switch.log \
    || cat nixos-switch.log | rg --color=always error && false
gen=$(nixos-rebuild list-generations | rg current)
git commit -am "$gen"
