#!/usr/bin/env bash

NIX_HOST_PATH=$HOME/.config/nixos/host

function new_host {
    echo "Generating hardware config..."
    read -p "New host name ($(hostname)):" host

    if [[ -z $host ]]; then
        host=$(hostname)
    fi

    mkdir ./hosts/${host}
    nixos-generate-config --show-hardware-config > hosts/${host}/hardware-configuration.nix
    echo $host
}

function choose_host {
    # if host path doesn't exist, choose one
    if [[ ! -e $NIX_HOST_PATH || ! -s $NIX_HOST_PATH ]]; then
        mkdir -p $(dirname $NIX_HOST_PATH)
        choices=$(find ./hosts/* -maxdepth 1 -type d -exec basename {} \;)
        choice=$(echo $choices | sed 's/^/new_host /' | sed 's/ /\n/g' | fzf --height 10%)
        if [[ $choice == "new_host" ]]; then
            choice=$(new_host)
        fi
        echo $choice > $NIX_HOST_PATH
    fi
}

cd ~/.dotfiles/nixos
echo "Rebuilding ❄️NixOS..."

choose_host

git diff -U0 **/*.nix
sudo nixos-rebuild switch --impure --flake .#$(cat $NIX_HOST_PATH) &>nixos-switch.log

if [[ $? -gt 0 ]]; then
    echo "Build failed..."
    cat nixos-switch.log | rg --color=always error
else
    git commit -am "$(nixos-rebuild list-generations | rg current)"
fi

