#!/usr/bin/env bash

if [[ -n "$TMUX" ]]; then

    tmux select-pane -t _

    cols=$COLUMNS
    moon_w=67
    weather_w=126

    tmux send-keys 'moon' C-m
    tmux split-window -l $(( cols - moon_w )) -h 'weather'
    tmux split-window -l $(( cols - (moon_w + weather_w) )) -h 'htop'
    tmux split-window -vf
    tmux split-window -h 'cmus'
    tmux select-pane -t 1.3
    tmux send-keys 'vim -c ":ObsidianToday"' C-m

fi
