#!/usr/bin/env bash

if [[ -n "$TMUX" ]]; then

    tmux select-pane -t _

    moon_w=67
    weather_w=126

    tmux send-keys 'htop' C-m
    tmux split-window -l $(( moon_w + weather_w )) -h 'weather'
    tmux split-window -l $(( moon_w )) -h 'moon'
    tmux split-window -vf
    tmux split-window -h 'cmus'
    tmux select-pane -t 1.3
    tmux send-keys 'vim -c ":ObsidianToday"' C-m

fi
