#!/usr/bin/env bash

DEEPGRAM_API_KEY="$(head -1 "$HOME/.config/deepgram/token")"

mkdir -p /tmp/dictation

# check for filename or use timestamp
if [ $# -gt 0 ]; then
    filename=$(echo $@ | sed 's/ /_/g')
else
    filename=$(date +%s)
fi

file_loc="/tmp/dictation/$filename.mp3"

parecord $file_loc &
parec_pid=$!

echo "recording. press q to stop"

# loop waits for 'q' and stops recording
while :
do
    read -n 1 key
    if [ "$key" = "q" ]; then
        echo && echo "stopping recording..."
        sleep 2s
        kill -SIGINT $parec_pid
        break
    fi
done

echo "${file_loc} saved."

output_loc=$(echo $file_loc | sed 's/mp3/json/')

echo 'analyzing audio...'
curl -so $output_loc \
  --request POST \
  --header "Authorization: Token ${DEEPGRAM_API_KEY}" \
  --header 'Content-Type: audio/wav' \
  --data-binary @$file_loc \
  --url 'https://api.deepgram.com/v1/listen?model=nova-2&smart_format=true'

echo "${output_loc} saved."

transcript=$(cat $output_loc \
    | jq ".results.channels[].alternatives[].transcript")

echo $transcript | sed 's/^"\(.*\)"$/\1/' | xclip -i -selection clipboard

echo $transcript
echo 'copied to clipboard'
