#!/usr/bin/env bash

# process flags
COPY=0
FILE=0
MULTI=0
SLUG=0
while getopts 'cfms' flag; do
    case "${flag}" in
        c) COPY=1;;     # copy the chosen emoji to the clipboard
        f) FILE=1;;     # don't remember what this was intended to do
        m) MULTI=1;;    # [TODO] look into this more; this flag essentially calls emoji_replace
        s) SLUG=1;;     # returns the slug instead of the emoji
        *) echo "Unexpected option ${flag}"
        exit 1 ;;
    esac
done

# drop processed arguments
shift $((OPTIND-1))

# set input according to environment
if [ -n "$VIMRUNTIME" ] || [ ! -t 0 ]; then
    INPUT="$(cat)"
else
    INPUT="$*"
fi

# get emojis and slugs
EMOJIS=$(jq -r '.[] | "\(.character) \(.slug | sub("e[0-9]+-[0-9]+-"; ""))"' < "$HOME/.dotfiles/data/emoji.json" )


function get_emoji() {
    # look for match on user input
    local MATCH
    local CHOICE

    MATCH=$(echo "$EMOJIS" | awk '{print $2}' | rg -x "$(echo "$1" | tr ' ' '-')")
    if [ -n "$MATCH" ]; then
        # if there's a match, return it
        CHOICE=$(echo "$EMOJIS" | rg ".*\\s$MATCH$")
    else
        # avoid using fzf when calling from inside vim
        if [ -z "$VIMRUNTIME" ]; then
            CHOICE=$(echo "$EMOJIS" | fzf --height=~10 --select-1 --exit-0 --query="$*")
        else
            echo "$* not found"
            exit 1
        fi
    fi

    # if the -s flag was used, we want to return the slug string
    # instead of the emoji unicode value
    output_val=$((SLUG + 1))

    # flagged behavior
    if [ $COPY -gt 0 ]; then
        # copy to clipboard
        echo "$CHOICE" | awk "{printf \"%s\", \$$output_val}" | xclip -selection 'clipboard' -i
    else
        # print to terminal
        echo "$CHOICE" | awk "{print \$$output_val}"
    fi
}

function emoji_replace() {
    local output="$*"
    local slug
    local emoji

    # gather up pattern matches
    declare -A matches
    while IFS= read -r match; do
        if [ "${matches[$match]}" ]; then continue; fi

        # strip off colons
        slug=${match//:/}
        emoji=$(get_emoji "$slug")

        if [[ "$emoji" != *"not found" ]]; then
            matches["$match"]="$emoji"
        fi

    done < <(echo "$output" | rg -oNr '$0' ':[-\w]+:')

    # replace them with their emoji unicode
    for match in "${!matches[@]}"; do
        output="${output//$match/${matches[$match]}}"
    done

    echo "$output"
}


if [ $MULTI -gt 0 ]; then
    emoji_replace "$INPUT"
else
    get_emoji "$INPUT"
fi
