#!/usr/bin/env bash

if [[ $(xrandr | rg -c " connected") -gt 1 ]]; then
    xrandr \
    --output DP-0 \
    --primary \
    --rotate right \
    --output HDMI-0 \
    --right-of DP-0 \
    --output eDP-1-1 \
    --right-of HDMI-0
else
    xrandr --output eDP-1-1 --primary
fi

