#!/usr/bin/env bash

if [ "$*" == "status" ]; then
    # the status command should return the status
    curl -s http://192.168.0.102:7666/$*
else
    # other commands shouldn't return anything
    curl -s http://192.168.0.102:7666/$* > /dev/null
    ~/.dotfiles/scripts/pomos_today > /tmp/pomos
fi
