#!/usr/bin/env bash

POMO_URL="http://192.168.0.102:7666/"

pm_count=$(curl -s "$POMO_URL/status" | jq .pomos_today)

d=4
m=$((pm_count / d))
r=$((pm_count % d))

tens=$(echo $m | xargs -I % sh -c 'yes ":canned-food:" | head -n % | xargs')
ones=$(echo $r | xargs -I % sh -c 'yes ":tomato:" | head -n % | xargs')

echo "$ones $tens" | sed 's/ //g' | emoji -m
