#!/usr/bin/bash

stus=$(curl -s http://127.0.1.1:7666/status)
event=$(echo $stus | jq -r .event)
time=$(echo $stus | jq -r '.time_remaining | "\(.min):\(.sec)"')
exceeded=$(echo $stus | jq -r .time_remaining.time_exceeded)

e=''
if [ $time == "null:null" ] || [ $event == "stop" ]; then
    exit
elif [ $event == "break" ]; then
    if [ $exceeded -gt 0 ]; then
        e=":hourglass-done:-"
    else
        e=":hourglass-not-done:"
    fi
elif [ $event == "pause" ]; then
    e=":zzz:"
else
    if [ $exceeded -gt 0 ]; then
        e=":anger-symbol:-"
    else
        e=":tomato:"
    fi
fi

echo "[$e$time]" | emoji -m
