#!/usr/bin/env bash

POMO_URL="http://robot-house:7666/"
WARN='01:00'
WARN_MSG="🍅⌚One minute remaining!"
EXCEEDED_MSG="🍅‼️Time for a break!"


stus=$(curl -s $POMO_URL/status)
event=$(echo "$stus" | jq -r .event)
time=$(echo "$stus" | jq -r '.time_remaining | "\(.min):\(.sec)"')
exceeded=$(echo "$stus" | jq -r .time_remaining.time_exceeded)
min=$(echo "$stus" | jq -r .min)


emoji=''
if [ "$time" == "null:null" ] || [ "$event" == "stop" ]; then
    exit
elif [ "$event" == "break" ]; then
    if [ "$exceeded" -gt 0 ]; then
        emoji=":hourglass-done:-"
    else
        emoji=":hourglass-not-done:"
    fi
elif [ "$event" == "pause" ]; then
    emoji=":zzz:"
else
    if [ "$exceeded" -gt 0 ]; then
        emoji=":anger-symbol:-"
    else
        emoji=":tomato:"
    fi
fi


echo "[$emoji$time]" | emoji -m


if [ "$time" == $WARN ]; then
    tmux display-message -d 2000 "$WARN_MSG"
    notify-send -u low "$WARN_MSG"
fi

if [ "$time" == "00:00" ]; then
    tmux display-message -d 2000 "$EXCEEDED_MSG"
    notify-send -u low "$EXCEEDED_MSG"
fi
