#!/usr/bin/env bash

pm_count=$(curl -s 192.168.0.130:7666/status | jq .pomos_today)

d=4
m=$(($pm_count / $d))
r=$(($pm_count % $d))

tens=$(echo $m | xargs -I % sh -c 'yes ":canned-food:" | head -n % | xargs')
ones=$(echo $r | xargs -I % sh -c 'yes ":tomato:" | head -n % | xargs')

echo "$ones $tens" | sed 's/ //g' | emoji -m
