#!/usr/bin/env bash

POMO_URL="http://robot-house:7666/"

if [ "$*" == "status" ]; then
    # the status command should return the status
    curl -s "$POMO_URL/$*"
else
    # other commands shouldn't return anything
    curl -s  "$POMO_URL/$*" > /dev/null
    ~/.dotfiles/scripts/pomos_today > /tmp/pomos
fi
