#!/usr/bin/env bash

# tmux-sessionizer
# stolen & adapted from ThePrimeagen

dirs="$HOME/ $HOME/Repos $HOME/work $HOME/work/*/Repos"
addtl="_\n/tmp/scratch"

# user can provide an argument, else find from list of directories
if [[ $# -eq 1 ]]; then
    target_dir=$1
else
    found=$(find $dirs -maxdepth 1 -mindepth 1 -type d)
    all_choices="${found}\n${addtl}"
    target_dir=$(echo -e "${all_choices}"| fzf)
fi

# if no target, exit
if [[ -z $target_dir ]]; then
    exit 0
fi

target_name=$(basename "$target_dir" | tr . _)
tmux_running=$(pgrep tmux)

# if not connected to tmux and tmux is not running
if [[ -z $TMUX ]] || [[ -z $tmux_running ]]; then
    tm
fi

if ! tmux has-session -t="$target_name" 2> /dev/null; then
    tmux new-session -ds "$target_name" -c "$target_dir"
fi

tmux switch-client -t "$target_name"

