#!/usr/bin/env bash

function session_exists {
    if tmux list-sessions | grep "$1"; then
        return 0
    else
        return 1
    fi
}

# Only start new sessions if they don't already exist
if ! pgrep -x 'tmux' > /dev/null || [[ -n $(session_exists "_") ]]; then

    tmux new-session -d -s _ 'htop'
    tmux rename-window -t _ 'main'

    tmux split-window -t _ -l 67 -h 'moon'
    tmux split-window -t _ -vf
    tmux split-window -t _:1.2 -l 125 -h 'weather'

fi

if [[ -z "$TMUX" ]]; then
    # attach to session 1 if exists and not already attached to a session
    tmux attach-session -t _:1.1
else
    # put focus for session 1 on the bottom left pane
    tmux select-pane -t _:1.1
fi
