#!/usr/bin/env bash

cd "$HOME/.dotfiles/nixos/modules" || exit

function update {
    flake=$(realpath ./"$1"/flake.nix)
    url=$(rg "url = \"https" "$flake" | sed -n 's/.*url = "\(.*\)";/\1/p')
    [[ -z "$url"  ]] && return
    old_hash=$(rg sha256 "$flake" | sed -n 's/\s*sha256 = "\(sha256-.*=\)";/\1/p')
    [[ -z "$old_hash"  ]] && return
    new_hash=$(nix-prefetch-git --quiet "$url" | jq -r ".hash")
    if [[ "*$old_hash*" != *$new_hash* ]]; then
        echo "updating $flake"
        sed -i "s|$old_hash|$new_hash|" "$flake"
    fi
}

function update_all {
    modules=$(find ./* -maxdepth 0 -type d -exec basename {} \;)
    for dir in $modules; do
        update "$dir"
    done
}

update_all
