#!/usr/bin/env bash

read -r x y width height <<< "$(slop -f "%x %y %w %h")"
ffmpeg -f x11grab -video_size "${width}"x"${height}" -i :0+"$x","$y" -filter_complex \
  "[0:v] fps=10,scale=320:-1:flags=lanczos,split [a][b];[a] palettegen=max_colors=64 [p];[b][p] paletteuse=dither=bayer:bayer_scale=5" \
  output.gif
