#!/usr/bin/env bash

vpn = function {
    if ! openvpn3 sessions-list | rg "Config name" | rg cl >/dev/null 2>&1; then
        # if no session found...

        if ! openvpn3 configs-list | rg cl >/dev/null 2>&1; then
            # if no config found, import one
            openvpn3 config-import --config /home/n/.ovpn/profile-140.ovpn --name cl --persistent
        fi

        # connect
        openvpn3 session-start -c cl
    else
        # if session is found, disconnect
        openvpn3 session-manage -c cl --disconnect
    fi
}
