#!/bin/bash

func() {
    local np=$(~/.dotfiles/scripts/now_playing)
    #local os=$(~/.dotfiles/scripts/obs_status)
    local pt=$(~/.dotfiles/scripts/pomo_time)

    local lout="$pt$np"
    local rout="[$(date +"%H:%M %a %b %d")]"

    local ww=$(tmux display-message -p "#{window_width}")
    local hw=$(($ww / 2))
    local rw=$(($ww / 3 * 2))

    local space=$(($hw - ${#lout} / 2 - ${#rout} - 2))
    local output="$lout$(printf "%*s" $space)$rout"

    tmux set -g status-right-length $(( ${#output} + 2 ))
    echo "$output"
}

func
