#!/usr/bin/env bash

# https://github.com/grigio/obs-cmd


function streamsaver() {

    local cmd="cbonsai -li -t 0.15 -w 1"

    cam && mute

    if [ -n "$*" ]; then
        cmd="$cmd -m \"$*\""
    fi

    tmux display-popup -E "$cmd"

    cam && mute

}


alias obs-studio="\$(which obs)"
alias obs="obs-cmd --websocket obsws://localhost:4445/\$(head -1 \$HOME/.config/obs-studio/token)"
alias cam="obs scene-item toggle cam zerocam &> /dev/null"
alias blur="obs scene-item toggle desktop1 'HDMI-0 blur' &> /dev/null"
alias camstat="obs scene-item toggle cam static &> /dev/null"
alias mute="obs toggle-mute Mic/Aux &> /dev/null"
alias dtmute="obs toggle-mute 'Desktop Audio' &> /dev/null"
alias sbreak="streamsaver &> /dev/null"
alias switch="obs scene switch"
alias sw="switch"
